mdq_question:
    resource: "@MDQQuestionBundle/Resources/config/routing.yml"
    prefix:   /question

mdq_quizz:
    resource: "@MDQQuizzBundle/Resources/config/routing.yml"
    prefix:   /quizz

mdq_user:
    resource: "@MDQUserBundle/Resources/config/routing.yml"
    prefix:   /user

mdq_gene:
    resource: "@MDQGeneBundle/Resources/config/routing.yml"
    prefix:   /

mdq_admin:
    resource: "@MDQAdminBundle/Resources/config/routing.yml"
    prefix:   /bossMDQ
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

fos_user_security_login:
    path:      /goToMDQ
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }
    
fos_user_registration_register:
    path:      /newToMDQ
    defaults:  { _controller: FOSUserBundle:Registration:register }
    methods:  [GET, POST]
    
fos_user_resetting_request:
    path:      /resetPass
    defaults:  { _controller: FOSUserBundle:Resetting:request }
    methods:  [GET, POST]
