# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
                  

    mdq_gene.repository.date_ref:
        class: MDQ\GeneBundle\Entity\DateReference
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments: ['MDQGeneBundle:DateReference']

    mdq_admin.repository.gestion:
        class: MDQ\AdminBundle\Entity\Gestion
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments: ['MDQAdminBundle:Gestion']      

    mdq_quizz.repository.partiequizz:
        class: MDQ\QuizzBundle\Entity\PartieQuizz
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments: ['MDQQuizzBundle:PartieQuizz']
        
    mdq_user.repository.scuser:
        class: MDQ\UserBundle\Entity\ScUser
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments: ['MDQUserBundle:ScUser']
        
    mdq_user.repository.user:
        class: MDQ\UserBundle\Entity\User
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments: ['MDQUserBundle:User']
       
    mdq_gene.service.role:
        class: MDQ\GeneBundle\Services\RoleService
        arguments: ['@security.role_hierarchy']
        
    mdq_admin.security:
        class: MDQ\AdminBundle\Services\SelfSecurity
        arguments: ['@security.token_storage', '@security.authorization_checker', '@session', '@mdq_admin.repository.gestion']

