parameters:
#    mdq_quizz.example.class: MDQ\QuizzBundle\Example

services:
#    mdq_quizz.example:
#        class: %mdq_quizz.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

     mdq_quizz.services:         
         class: MDQ\QuizzBundle\Services\QuizzServ
         arguments: [@mdq_user.jeton_serv, @mdq_admin.repository.gestion]
         
     mdq_quizz.ajax:         
         class: MDQ\QuizzBundle\Services\AjaxQuizz
