mdqquestion_ajouterQ:
    path:    /ajouterQ
    defaults: { _controller: MDQQuestionBundle:Question:ajouterQ }
    methods:  [GET, POST]
mdqquestion_modifQaval:
    path:    /modifQaval/{id}
    defaults: { _controller: MDQQuestionBundle:Question:modifQaval}
    methods:  [GET, POST]
mdqquestion_adaptForm:
    path:    /adaptForm
    defaults: { _controller: MDQQuestionBundle:Question:adaptForm }
    methods:  [GET]
