parameters:
#    mdq_user.example.class: MDQ\UserBundle\Example

services:
    mdq_user.registration.form.type:
        class: MDQ\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mdq_user_registration }
    mdq_user.profile.form.type:
        class: MDQ\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: mdq_user_profile }
    mdq_user.jeton_serv:         
        class: MDQ\UserBundle\Services\JetonServ
        arguments: ['@mdq_admin.repository.gestion']
    mdq_user.usertwig:
        class: MDQ\UserBundle\Services\UserTwig
        arguments: ['@mdq_gene.repository.date_ref']


