parameters:
#    mdq_admin.example.class: MDQ\AdminBundle\Example

services:
#    mdq_admin.example:
#        class: %mdq_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

     mdq_admin.botGame:
         class: MDQ\AdminBundle\Services\BotGame
         
     mdq_admin.adminTwig:
         class: MDQ\AdminBundle\Services\AdminTwig
         arguments: [@twig.extension.assets]        
         
     mdq_admin.gestionQ:
         class: MDQ\AdminBundle\Services\GestionQuestion

     mdq_admin.stats:
         class: MDQ\AdminBundle\Services\StatServ
